pipeline:
  build-debian:
    image: pexeso/pexeso-build-debian:9.3
    commands:
      - apt-get update
      - apt-get install -y libevent-dev python-docutils devscripts build-essential lintian
      - git submodule init
      - git submodule update
      - ./autogen.sh
      - ./configure --with-pmgr
      - make
      - make deb
      - mkdir -p proto/debian/
      - mv ../*.deb proto/debian/
      - ls -lR proto
      - dpkg -c proto/debian/*.deb
  build-ubuntu:
    image: pexeso/pexeso-build-ubuntu:16.04
    commands:
      - apt-get update
      - apt-get install -y libevent-dev python-docutils devscripts build-essential lintian dh-systemd
      - git submodule init
      - git submodule update
      - ./autogen.sh
      - ./configure --with-pmgr
      - make
      - make deb
      - mkdir -p proto/ubuntu/
      - mv ../*.deb proto/ubuntu/
      - ls -lR proto
      - dpkg -c proto/debian/*.deb

