pipeline:
  build-debian:
    group: build
    image: pexeso/pexeso-build-debian:9.3
    commands:
      - git submodule init
      - git submodule update
      - ./autogen.sh
      - ./configure --with-pmgr
  build-ubuntu:
    group: build
    image: pexeso/pexeso-build-ubuntu:16.04
    commands:
      - git submodule init
      - git submodule update
      - ./autogen.sh
      - ./configure --with-pmgr
  deploy:
    artifactory:
      image: athieriot/drone-artifactory
      url: stretch-url
      username: ${artifactory_user}
      password: ${artifactory_user}
      files:
        - ../*.deb
